/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YamlJsonRouteImport } from './routes/yaml-json'
import { Route as XmlRouteImport } from './routes/xml'
import { Route as UuidRouteImport } from './routes/uuid'
import { Route as UrlRouteImport } from './routes/url'
import { Route as SqlVisualizerRouteImport } from './routes/sql-visualizer'
import { Route as SqlFormatterRouteImport } from './routes/sql-formatter'
import { Route as RegexRouteImport } from './routes/regex'
import { Route as MockApiRouteImport } from './routes/mock-api'
import { Route as JwtRouteImport } from './routes/jwt'
import { Route as JsonDiffRouteImport } from './routes/json-diff'
import { Route as JsonRouteImport } from './routes/json'
import { Route as HttpStatusRouteImport } from './routes/http-status'
import { Route as HashRouteImport } from './routes/hash'
import { Route as GraphqlRouteImport } from './routes/graphql'
import { Route as EpochRouteImport } from './routes/epoch'
import { Route as EnvRouteImport } from './routes/env'
import { Route as DiffRouteImport } from './routes/diff'
import { Route as CsvJsonRouteImport } from './routes/csv-json'
import { Route as CronRouteImport } from './routes/cron'
import { Route as ColorRouteImport } from './routes/color'
import { Route as Base64RouteImport } from './routes/base64'
import { Route as IndexRouteImport } from './routes/index'

const YamlJsonRoute = YamlJsonRouteImport.update({
  id: '/yaml-json',
  path: '/yaml-json',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlRoute = XmlRouteImport.update({
  id: '/xml',
  path: '/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UuidRoute = UuidRouteImport.update({
  id: '/uuid',
  path: '/uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlRoute = UrlRouteImport.update({
  id: '/url',
  path: '/url',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlVisualizerRoute = SqlVisualizerRouteImport.update({
  id: '/sql-visualizer',
  path: '/sql-visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlFormatterRoute = SqlFormatterRouteImport.update({
  id: '/sql-formatter',
  path: '/sql-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexRoute = RegexRouteImport.update({
  id: '/regex',
  path: '/regex',
  getParentRoute: () => rootRouteImport,
} as any)
const MockApiRoute = MockApiRouteImport.update({
  id: '/mock-api',
  path: '/mock-api',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtRoute = JwtRouteImport.update({
  id: '/jwt',
  path: '/jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonDiffRoute = JsonDiffRouteImport.update({
  id: '/json-diff',
  path: '/json-diff',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonRoute = JsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpStatusRoute = HttpStatusRouteImport.update({
  id: '/http-status',
  path: '/http-status',
  getParentRoute: () => rootRouteImport,
} as any)
const HashRoute = HashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlRoute = GraphqlRouteImport.update({
  id: '/graphql',
  path: '/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const EpochRoute = EpochRouteImport.update({
  id: '/epoch',
  path: '/epoch',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvRoute = EnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffRoute = DiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvJsonRoute = CsvJsonRouteImport.update({
  id: '/csv-json',
  path: '/csv-json',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoute = ColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64Route = Base64RouteImport.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base64': typeof Base64Route
  '/color': typeof ColorRoute
  '/cron': typeof CronRoute
  '/csv-json': typeof CsvJsonRoute
  '/diff': typeof DiffRoute
  '/env': typeof EnvRoute
  '/epoch': typeof EpochRoute
  '/graphql': typeof GraphqlRoute
  '/hash': typeof HashRoute
  '/http-status': typeof HttpStatusRoute
  '/json': typeof JsonRoute
  '/json-diff': typeof JsonDiffRoute
  '/jwt': typeof JwtRoute
  '/mock-api': typeof MockApiRoute
  '/regex': typeof RegexRoute
  '/sql-formatter': typeof SqlFormatterRoute
  '/sql-visualizer': typeof SqlVisualizerRoute
  '/url': typeof UrlRoute
  '/uuid': typeof UuidRoute
  '/xml': typeof XmlRoute
  '/yaml-json': typeof YamlJsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base64': typeof Base64Route
  '/color': typeof ColorRoute
  '/cron': typeof CronRoute
  '/csv-json': typeof CsvJsonRoute
  '/diff': typeof DiffRoute
  '/env': typeof EnvRoute
  '/epoch': typeof EpochRoute
  '/graphql': typeof GraphqlRoute
  '/hash': typeof HashRoute
  '/http-status': typeof HttpStatusRoute
  '/json': typeof JsonRoute
  '/json-diff': typeof JsonDiffRoute
  '/jwt': typeof JwtRoute
  '/mock-api': typeof MockApiRoute
  '/regex': typeof RegexRoute
  '/sql-formatter': typeof SqlFormatterRoute
  '/sql-visualizer': typeof SqlVisualizerRoute
  '/url': typeof UrlRoute
  '/uuid': typeof UuidRoute
  '/xml': typeof XmlRoute
  '/yaml-json': typeof YamlJsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/base64': typeof Base64Route
  '/color': typeof ColorRoute
  '/cron': typeof CronRoute
  '/csv-json': typeof CsvJsonRoute
  '/diff': typeof DiffRoute
  '/env': typeof EnvRoute
  '/epoch': typeof EpochRoute
  '/graphql': typeof GraphqlRoute
  '/hash': typeof HashRoute
  '/http-status': typeof HttpStatusRoute
  '/json': typeof JsonRoute
  '/json-diff': typeof JsonDiffRoute
  '/jwt': typeof JwtRoute
  '/mock-api': typeof MockApiRoute
  '/regex': typeof RegexRoute
  '/sql-formatter': typeof SqlFormatterRoute
  '/sql-visualizer': typeof SqlVisualizerRoute
  '/url': typeof UrlRoute
  '/uuid': typeof UuidRoute
  '/xml': typeof XmlRoute
  '/yaml-json': typeof YamlJsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/base64'
    | '/color'
    | '/cron'
    | '/csv-json'
    | '/diff'
    | '/env'
    | '/epoch'
    | '/graphql'
    | '/hash'
    | '/http-status'
    | '/json'
    | '/json-diff'
    | '/jwt'
    | '/mock-api'
    | '/regex'
    | '/sql-formatter'
    | '/sql-visualizer'
    | '/url'
    | '/uuid'
    | '/xml'
    | '/yaml-json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/base64'
    | '/color'
    | '/cron'
    | '/csv-json'
    | '/diff'
    | '/env'
    | '/epoch'
    | '/graphql'
    | '/hash'
    | '/http-status'
    | '/json'
    | '/json-diff'
    | '/jwt'
    | '/mock-api'
    | '/regex'
    | '/sql-formatter'
    | '/sql-visualizer'
    | '/url'
    | '/uuid'
    | '/xml'
    | '/yaml-json'
  id:
    | '__root__'
    | '/'
    | '/base64'
    | '/color'
    | '/cron'
    | '/csv-json'
    | '/diff'
    | '/env'
    | '/epoch'
    | '/graphql'
    | '/hash'
    | '/http-status'
    | '/json'
    | '/json-diff'
    | '/jwt'
    | '/mock-api'
    | '/regex'
    | '/sql-formatter'
    | '/sql-visualizer'
    | '/url'
    | '/uuid'
    | '/xml'
    | '/yaml-json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Base64Route: typeof Base64Route
  ColorRoute: typeof ColorRoute
  CronRoute: typeof CronRoute
  CsvJsonRoute: typeof CsvJsonRoute
  DiffRoute: typeof DiffRoute
  EnvRoute: typeof EnvRoute
  EpochRoute: typeof EpochRoute
  GraphqlRoute: typeof GraphqlRoute
  HashRoute: typeof HashRoute
  HttpStatusRoute: typeof HttpStatusRoute
  JsonRoute: typeof JsonRoute
  JsonDiffRoute: typeof JsonDiffRoute
  JwtRoute: typeof JwtRoute
  MockApiRoute: typeof MockApiRoute
  RegexRoute: typeof RegexRoute
  SqlFormatterRoute: typeof SqlFormatterRoute
  SqlVisualizerRoute: typeof SqlVisualizerRoute
  UrlRoute: typeof UrlRoute
  UuidRoute: typeof UuidRoute
  XmlRoute: typeof XmlRoute
  YamlJsonRoute: typeof YamlJsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yaml-json': {
      id: '/yaml-json'
      path: '/yaml-json'
      fullPath: '/yaml-json'
      preLoaderRoute: typeof YamlJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml': {
      id: '/xml'
      path: '/xml'
      fullPath: '/xml'
      preLoaderRoute: typeof XmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uuid': {
      id: '/uuid'
      path: '/uuid'
      fullPath: '/uuid'
      preLoaderRoute: typeof UuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url': {
      id: '/url'
      path: '/url'
      fullPath: '/url'
      preLoaderRoute: typeof UrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-visualizer': {
      id: '/sql-visualizer'
      path: '/sql-visualizer'
      fullPath: '/sql-visualizer'
      preLoaderRoute: typeof SqlVisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-formatter': {
      id: '/sql-formatter'
      path: '/sql-formatter'
      fullPath: '/sql-formatter'
      preLoaderRoute: typeof SqlFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex': {
      id: '/regex'
      path: '/regex'
      fullPath: '/regex'
      preLoaderRoute: typeof RegexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-api': {
      id: '/mock-api'
      path: '/mock-api'
      fullPath: '/mock-api'
      preLoaderRoute: typeof MockApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt': {
      id: '/jwt'
      path: '/jwt'
      fullPath: '/jwt'
      preLoaderRoute: typeof JwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-diff': {
      id: '/json-diff'
      path: '/json-diff'
      fullPath: '/json-diff'
      preLoaderRoute: typeof JsonDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json': {
      id: '/json'
      path: '/json'
      fullPath: '/json'
      preLoaderRoute: typeof JsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-status': {
      id: '/http-status'
      path: '/http-status'
      fullPath: '/http-status'
      preLoaderRoute: typeof HttpStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash': {
      id: '/hash'
      path: '/hash'
      fullPath: '/hash'
      preLoaderRoute: typeof HashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql': {
      id: '/graphql'
      path: '/graphql'
      fullPath: '/graphql'
      preLoaderRoute: typeof GraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epoch': {
      id: '/epoch'
      path: '/epoch'
      fullPath: '/epoch'
      preLoaderRoute: typeof EpochRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/env': {
      id: '/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof EnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv-json': {
      id: '/csv-json'
      path: '/csv-json'
      fullPath: '/csv-json'
      preLoaderRoute: typeof CsvJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color': {
      id: '/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof ColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64': {
      id: '/base64'
      path: '/base64'
      fullPath: '/base64'
      preLoaderRoute: typeof Base64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Base64Route: Base64Route,
  ColorRoute: ColorRoute,
  CronRoute: CronRoute,
  CsvJsonRoute: CsvJsonRoute,
  DiffRoute: DiffRoute,
  EnvRoute: EnvRoute,
  EpochRoute: EpochRoute,
  GraphqlRoute: GraphqlRoute,
  HashRoute: HashRoute,
  HttpStatusRoute: HttpStatusRoute,
  JsonRoute: JsonRoute,
  JsonDiffRoute: JsonDiffRoute,
  JwtRoute: JwtRoute,
  MockApiRoute: MockApiRoute,
  RegexRoute: RegexRoute,
  SqlFormatterRoute: SqlFormatterRoute,
  SqlVisualizerRoute: SqlVisualizerRoute,
  UrlRoute: UrlRoute,
  UuidRoute: UuidRoute,
  XmlRoute: XmlRoute,
  YamlJsonRoute: YamlJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
